### PR TITLE
Missing .pl in various files

### PR DESCRIPTION
**Pull request by jpthiele**
I just noticed some missing endings in some of the files.
With this, the indent check should pass.

### CODE REVIEW

**Comment by bangerth** [comment]
You'll have to make this a pull request against the deal.II repo, not mine :-)

**Comment by bangerth** [comment]
But I think I already have these files covered in https://github.com/dealii/dealii/pull/16048, please check.

**Comment by bangerth** [comment]
Oh, I see now why you're doing this against my branch. I had forgotten to commit some files and fixed that before seeing your patch here.

**Comment by jpthiele** [comment]
I think the `update-copyright.sh` in contrib/utilities is still missing. Apart from that it looks good.

**Comment by bangerth** [comment]
I see, yes. Another place where I didn't pay enough attention. Would you like me to do that one, or do you want to get the credit for it?

**Pull request closed without merging**
