### PR TITLE
Step 71

### PR DESCRIPTION
**Pull request by sophy1029**
I checked the penalties in face_worker and boundary_worker. Both of them use p(p+1).
I ran it and got the same num. solutions as in the tables of results.dox.
And I suppose " documention " is a typo?

### CODE REVIEW

**Comment by bangerth** [comment]
Great, thanks!

**Comment by sophy1029** [comment]
Please let me know if there's anything else I can help with.

**Comment by bangerth** [comment]
Actually, I do. The `boundary_worker` uses `2*gamma`, but the `face_worker` only `gamma`. Is this as it should be if you compare with the paper?

**Comment by sophy1029** [comment]
Actually, no. In the paper, they have the same penalty.
I suppose we talked about this before.
I compared the results from taking gamma in boundary_worker and 2*gamma in
boundary worker, with the same penalty p = k(k+1),
their errors are pretty close. But 2*gamma converges better when k = 2.
So I suppose 2*gamma maybe better than taking gamma.

Shall we add a subsection in results.dox discussing this choice?

**Pull request merged**
